src/blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import settings
from posts.views import BlogHome

urlpatterns = [
                  path('', BlogHome.as_view(), name='home'),
                  path('admin/', admin.site.urls),
                  path('blog/', include('posts.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete
from django.contrib.auth.decorators import login_required

app_name = "posts"

urlpatterns = [
    path('', BlogHome.as_view(), name='home'),
    path('create/', login_required(BlogPostCreate.as_view()), name='create'),
    path('edit/<str:slug>/', BlogPostUpdate.as_view(), name='edit'),
    path('<str:slug>/', BlogPostDetail.as_view(), name='post'),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name='delete'),
]

src/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

User = get_user_model()


class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.TextField(blank=True, verbose_name="Contenu")
    thumbnail = models.ImageField(blank=True, upload_to='blog')

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    @property
    def author_or_default(self):
        return self.author.username if self.author else "L'autheur n'est pas connu"

    def get_absolute_url(self):
        return reverse('posts:home')

src/posts/views.py
from django.shortcuts import render

from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy

from posts.models import BlogPost


class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset

        return queryset.filter(published=True)


class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "posts/blogpost_create.html"
    fields = ['title', 'content', ]


class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = "posts/blogpost_update.html"
    fields = ['title', 'content', ]


class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"


class BlogPostDelete(DeleteView):
    model = BlogPost
    context_object_name = "post"
    success_url = reverse_lazy("posts:home")

src/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Supprimer un article</title>
{% endblock %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <p>Etes-vous sur de vouloir supprimer "{{ post.title }}"?</p>
        <input type="Submit" value="Oui supprimer" class="btn btn-delete">
    </form>

{% endblock %}

src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
    <title>Ajouter un article</title>
{% endblock %}

{% block content %}

    <h1>Ajouter un article</h1>

        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Creer" class="btn btn-submit">
        </form>

{% endblock %}

src/posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block content %}

    <article class="post-detail">
        <h1>{{ post.title }}</h1>
        <img src="{{ post.thumbnail.url }}" alt="L'image de l'article">
        <br></br>
        <div>{{ post.content|linebreaks|safe }}</div>
    </article>

{% endblock %}

src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Accueil du blog</title>
{% endblock %}

{% block content %}

    <h1>Le blog de Pydocs</h1>
    {% for post in posts %}
        <article>

            <div class="post-title">
                <h2>{{ post.title }}</h2>

                {% if request.user.is_authenticated %}
                <div>
                        <a href="{% url 'posts:edit' slug=post.slug %}">Editer</a>
                        <a href="{% url 'posts:delete' slug=post.slug %}">Supprimer</a>
                </div>
                {% endif %}

            </div>

            <h5 class="post-author">Publie par <i>{{ post.author_or_default }}</i> le {{ post.created_on|date:'j F Y' }}</h5>
            <p class="post-extrait">{{ post.content|safe|truncatewords:50 }}</p>

            <form action="{% url 'posts:post' slug=post.slug %}">
                <button class="btn btn-submit">Lire l'article</button>
            </form>

        </article>
    {% endfor %}

{% endblock %}

src/posts/templates/posts/blogpost_update.html
{% extends 'base.html' %}

{% block title %}
    <title>Modifier un article</title>
{% endblock %}

{% block content %}

    <h1>Modifier un article</h1>

        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Modifier" class="btn btn-submit">
        </form>

{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Accueil du Blog</title>
    {% endblock%}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<nav>
    <a href="{% url 'posts:home' %}">Accueil</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'posts:create' %}">Ajouter un article</a>
    {% endif %}
</nav>

<section id="blog">
    {% block content %}
    {% endblock %}
</section>

</body>
</html>